version: '3.4'
services:
  postgresql:
    container_name: dmp-postgresql
    image: postgres:14
    env_file:
      .env
    environment:
      POSTGRES_PASSWORD: ${LAJI_DMP_DATABASE_PWD}
      POSTGRES_USER: ${LAJI_DMP_DATABASE_USER}
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${LAJI_DMP_DATABASE_USER}"]
      interval: 5s
      timeout: 5s
      retries: 50
    network_mode: host
  dmp-backend:
    depends_on:
      postgresql:
        condition: service_healthy
    container_name: dmp-backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 4000:4000
    restart: 'always'
    network_mode: host
